### ISSUE TITLE
About the  Params and FLOPs of Laplacian-Former(with bridge)

### ISSUE THREAD

**Issue by 1580827935** [xmindflow/Laplacian-Former#1]
![图片](https://github.com/xmindflow/Laplacian-Former/assets/117509706/0b7ebf8e-7abd-4060-8cd2-84d24cb85ceb)
![图片](https://github.com/xmindflow/Laplacian-Former/assets/117509706/1240b8dc-e74d-47c3-b2ef-604c43ad59d3)

What are the parameters and FLOPs? Why can't I measure it? My result is 36.49M, not 27.54M?

**Comment by amirhossein-kz** [comment]
Hi @1580827935,

The number of `n_skip_bridge` is set to 1. By configuring it this way, you obtain 25.476M parameters and a FLOPs count of 6.485G. We used the [fvcore library](https://github.com/facebookresearch/fvcore) for calculating FLOPs and the number of parameters.

**Comment by 1580827935** [comment]
Yes, I obtained 25.476M parameters and a FLOPs count of 6.485G. But why are there not 27.54M parameters in your paper?
![图片](https://github.com/xmindflow/Laplacian-Former/assets/117509706/def6522f-a6fe-4909-a20a-cf5dddb16ff8)

**Comment by amirhossein-kz** [comment]
I've cleaned and optimized the code, leading to a reduced number of parameters. I've updated the table in the repo to reflect this change. I appreciate your attention to detail!

**Comment by 1580827935** [comment]
Ok, I see. Thank you very much for your answer and help!
